### PR TITLE
simple notebook showing how to make spheres of any size

### PR DESCRIPTION
**Pull request by nwstephens**
This example shows how to very easily make spheres of any size out of any material.

### CODE REVIEW

**Review by daroczig — APPROVED** [review]
This is great, thanks a lot :+1: 

On the other hand, I'm not sure if we want to maintain the extra vignettes folder here or move everything over to https://github.com/ropenscilabs/miner_book

@kbroman, what you think?

**Comment by kbroman** [comment]
This is cool. But yes, as @daroczig mentioned I have in mind that we keep the [miner](https://github.com/ropenscilabs/miner) package relatively clear and with just the basic functionality, and that we put higher-level functions (such as for making a sphere) in the [craft](https://github.com/ropenscilabs/craft) package, and extra vignettes as chapters in the [miner_book](https://github.com/ropenscilabs/miner_book). But I'm okay with stashing things in `extra_vignettes` and reorganizing later.

**Comment by nwstephens** [comment]
@daroczig and @kbroman, thanks for the feedback. It sounds like miner will remain clear, craft will contain higher level functions (like sphere), and miner_book will contain vignettes. It also sounds like extra_vignettes needs to be moved out of the miner package. I'm happy to cancel the pull request if someone wants to move the extra_vignettes to either craft or miner_book.

**Comment by nwstephens** [comment]
Also, please note I have three items to add now:
1. A "high-level" sphere function along with a vignette
2. An RStudio addin and shiny gadget for controlling the sphere. My kids love this gadget, because it lets them take control. The gadget requires changes in DESCRIPTION and and inst. My preference would be to put it into `craft`. Note: My gadget is still under development.
3. An vignette for how to create a Minecraft server on AWS. This is very similar to the install guide in the book already, except this script includes instructions for installing Java and opening ports and everything you would need from beginning to end on EC2.

**Comment by nwstephens** [comment]
I just want to put another plugin for [gadgets](https://shiny.rstudio.com/articles/gadgets.html). I think this would be great if we could see more people add gadgets to their Minecraft functions because they are kid friendly. Hopefully this is something that `craft` package will support.

**Comment by kbroman** [comment]
The RStudio addin and shiny gadget sound awesome. [craft](https://github.com/ropenscilabs/craft) does seem the right place for them, with vignettes in the package and/or as chapters in the [miner-book](https://github.com/ropenscilabs/miner-book).

Additional information to help people with installation would be super helpful. For sure, that's the main pain point for all of this.

**Comment by nwstephens** [comment]
Closing this pull request down to move content into craft and miner-book repos.

**Pull request closed without merging**
